import texpdfedits.utils as utils

EPILOG = f"""
-v --version
        Display program version

-d --debug
        Set logging level to DEBUG

-q --quiet
        Log only messages that are warnings or greater.
        The python logging library specifies five logging levels by default:

        DEBUG < INFO < WARN < ERROR < CRITICAL
            
        No log messages beneath the set level are written. So this option sets
        the logging level to WARN.

--clean 
        Delete intermediate files generated by TeX compilation
        The current list of extensions include:

        {utils.INTERMEDIATE_EXTENSIONS_TO_DELETE}

--update 
        Overwrite the provided pdf_file and latex_file with annotation status information
        Each annotation has a "checkmark" and "status" field. This program displays a UI to interact
        with those fields. When this option is true, it modifies the pdf_file based on how you
        interact with the UI. It also updates the corresponding annotation comments in the latex_file

        Here is an example annotation comment in the latex_file 

        Hall $\pi$%%
        %% Annotation 0, page 1 [✓] [ ] [None]
        %% Caret: "UBGROUPS AND<Caret> CHARACTERS "
        %% Comment: ","
        %%
        %⭣ ⭣ ⭣ 
        -subgroups and, characters %%
        %⭡ ⭡ ⭡  END of annotation 0

        The annotation statusses are listed after the page number. The first is made up and is only to
        track composition progress, the second reflects the pdf annotation's "checkmark" field, and the
        last its "status" field

-f --filter
        Filter which annotations are reviewed by a comma-separate list of key=value pairs.
        Available filters and how to specify their values are

        checkmark=True,
                Unlike author and status, the only accepted values are "True" or "False". Example:
                checkmark=False

        status=<statusses>,
                Just like author values. Example:
                status=None | Accepted

        author=<names>
                The author names can be any strings and multiple can be written separated by pipes "|". Example:
                author=CE | luke | john

        page=<numbers>,
                The page numbers are 1-based. Otherwise like author values. Example:
                page=1 | 2 | 7

        type=<types>,
                Just like author values. Example:
                type=Highlight | caret | ink        

        dates=<dates>,
                A date is written "month/day/year", otherwise like author values. Example:
                dates=1/24/1997 | 11/3/2026

        before_date=<date>,
                Give a single date like above. Example:
                before_date=1/23/2025

        after_date=<date>,
                Just like before_date.

        Whitespace is stripped from the key=value pairs, so it doesn't matter.
"""
