import logging
logger = logging.getLogger(__name__)
import pymupdf
import json
import re
import tempfile
import sys
import getpass

from pathlib import Path
from icecream import ic

import texpdfedits.utils as utils
import texpdfedits.extractanns as extractanns
import texpdfedits.vercorr.sync as sync

from texpdfedits.extractanns import Edit, XrefObj
from texpdfedits.vercorr.sync import SynctexOut

IMAGE_X_START = 30 # in points (TeX's big points)
BEFORE_AFTER_IMAGE_HEIGHT = 110

IMAGE_DPI = 130
SHOW_ANNS = True

BEFORE_SUBDIR = "before"
AFTER_SUBDIR = "after"

ATTENTION_BOX_GROW = 7.5 # also in points

class GuiAnnot:
    def __init__(self, man: Manuscript, edit: Edit):
        self.pageno = edit.pageno # 0-based
        self.page_label = edit.page_label
        _, self.type = edit.type
        self.comment = edit.message['comment']
        self.responses = edit.message['responses']
        self.xref = edit.xref
        self.related_xref = edit.related_xref
        self.checkmark = edit.checkmark
        self.status = edit.status
        
        # checkmark and status can be None in which case we'll
        # initialize them ourselves by creating new text annotations
        
        if self.checkmark is None:
            state_model = XrefObj.CHECKMARK_MODEL
            state = XrefObj.UNCHECKED
            self.checkmark = self.initialize_tannot(man, state_model, state)
            
        if self.status is None:
            state_model = XrefObj.STATUS_MODEL
            state = XrefObj.STATUS_NONE
            self.status = self.initialize_tannot(man, state_model, state)

        self.image_paths = man.xref_to_before_after_images[self.xref]

    def initialize_tannot(self, man: Manuscript, state_model: str, state: str) -> XrefObj:
        set_to = {
            XrefObj.FLAG_KEY: ('xref', XrefObj.FLAG_IN_USE),
            XrefObj.IRT_KEY: ('xref', f'{self.xref} 0 R'),
            XrefObj.STATE_MODEL_KEY: ('string', state_model),
            XrefObj.STATE_KEY: ('string', state),
            XrefObj.TITLE_KEY: ('string', man.user),
        }
        page = man.annots_pdf_doc[self.pageno]
        local_tannot = page.add_text_annot((0,0), '', icon='Comment')
        ta_xref = local_tannot.xref
        man.xref_update(ta_xref, set_to)
        return XrefObj(ta_xref, state_model, state, man.user)

class Manuscript:
    """Corrections manuscript"""
    def __init__(self, cl_args: argparse.Namespace):
        # misc.
        self.script_name = Path(sys.argv[0]).name
        self.user = getpass.getuser()

        # annotated PDF
        self.annots_pdf = Path(cl_args.annots_pdf)
        self.annots_pdf_doc, self.edits = self.extract_annotations()

        # .annin file
        self.annin_file = utils.replace_suffix(self.annots_pdf, 'annin')
        self.latex_file = Path(cl_args.latex_file)
        self.xref_to_line = self.initialize_xref_to_line()

        # latest pdf generated by LaTeX
        self.latex_pdf, self.generated_pdf_doc = self.generate_latest_pdf_from_latex(cl_args)

        # before/after images with SyncTeX
        self.ba_half_image_height = cl_args.image_height / 2        
        self.temp_dir_obj = tempfile.TemporaryDirectory()
        self.before_after_dir = Path(self.temp_dir_obj.name) # not the usual Path.name

        self.xref_to_synctex = {}
        self.xref_to_before_after_images = {}
        self.initialize_xref_to_before_after() # "fills in" above two
        
        logger.debug(f"Before/after images written to {self.before_after_dir}")

        self.gui_annotations = [
            GuiAnnot(self, edit)
            for edit in self.edits
        ]

    def regenerate_images(self, cl_args: argparse.Namespace):
        # .annin file
        self.xref_to_line = self.initialize_xref_to_line()

        # latest pdf generated by LaTeX
        self.latex_pdf, self.generated_pdf_doc = self.generate_latest_pdf_from_latex(cl_args)

        # before/after images with SyncTeX
        self.temp_dir_obj.cleanup() # remove old before/after images
        
        self.temp_dir_obj = tempfile.TemporaryDirectory()
        self.before_after_dir = Path(self.temp_dir_obj.name) # not the usual Path.name

        self.xref_to_synctex = {}
        self.xref_to_before_after_images = {}
        self.initialize_xref_to_before_after() # "fills in" above two
        
        logger.debug(f"Before/after images written to {self.before_after_dir}")

        # don't overwrite GUI annot fields other than the before/after image paths
        for gui_annot in self.gui_annotations:
            gui_annot.image_paths = self.xref_to_before_after_images[gui_annot.xref]
        
    ##################################################
    ##                                              ##
    ##            Initialization helpers            ##
    ##                                              ##
    ##################################################        

    def extract_annotations(self) -> tuple[pymupdf.Document, list[Edit]]:
        if not self.annots_pdf.exists():
            raise FileNotFoundError(f"Could not find annotated PDF '{annots_pdf}'")
        annots_pdf_doc = pymupdf.open(self.annots_pdf)
        edits, _ = extractanns.getEdits(
            self.annots_pdf,
            **{'adjust_annots': False},
        )
        return annots_pdf_doc, edits

    def initialize_xref_to_line(self) -> dict[int, int]:
        if not self.annin_file.exists():
            raise FileNotFoundError(f"Could not find {self.annin_file}")
        with open(self.annin_file, 'r') as f:
            xref_to_annidx = {}
            for line in f.readlines():
                line_json = json.loads(line)
                xref_to_annidx[line_json['xref']] = line_json['index']
        annidx_to_line = get_annidx_to_line(self.latex_file)
        xref_to_line = {
            xref : annidx_to_line.get(annidx, None)
            for xref, annidx in xref_to_annidx.items()
        }
        return xref_to_line

    def generate_latest_pdf_from_latex(self, cl_args: argparse.Namespace) -> tuple[Path, pymupdf.Document]:
        if not self.latex_file.exists():
            raise FileNotFoundError(f"Could not find LaTeX file '{latex_file}'")        
        if cl_args.gen_sync:
            utils.compile_tex(
                self.latex_file,
                cl_args.compiler,
                '-synctex=1',
            )
            dont_delete = [
                '.synctex.gz',
                '.synctex',
                '.pdf',
            ]
            utils.delete_intermediate_latex(self.latex_file, ignore=dont_delete)            
        latex_pdf = utils.replace_suffix(
            self.latex_file,
            'pdf',
        )
        if not latex_pdf.exists():
            raise FileNotFoundError(f"Could not find PDF generated by LaTeX file '{latex_pdf}'")
        generated_pdf_doc = pymupdf.open(latex_pdf.name)
        return latex_pdf, generated_pdf_doc

    def initialize_xref_to_before_after(self):
        logger.info("Generating before and after images...")
        
        num_edits = len(self.edits)
        bar = utils.TextProgressBar(num_edits, show_per=max(1, num_edits // 100))
        bar.showSize()

        before_dir = self.before_after_dir / BEFORE_SUBDIR
        after_dir = self.before_after_dir / AFTER_SUBDIR
        Path.mkdir(before_dir)
        Path.mkdir(after_dir)
                
        for edit in self.edits:
            acquire_synctex_out(self, edit)
            before_pixmap = get_before_pixmap(self, edit)
            before_img_path = self.save_and_get_img_path(
                edit,
                before_pixmap,
                before_dir,
            )
            after_pixmap = get_after_pixmap(self, edit)
            after_img_path = self.save_and_get_img_path(
                edit,
                after_pixmap,
                after_dir,
            )
            self.xref_to_before_after_images[edit.xref] = {
                    BEFORE_SUBDIR: before_img_path,
                    AFTER_SUBDIR: after_img_path,
            }
            bar.addProgress()
        bar.end()
        logger.info("Done")

    def set_synctex_out(self, xref: int, synctex_out: SynctexOut):
        line = self.xref_to_line[xref]
        self.xref_to_synctex[xref] = line, synctex_out        

    def save_and_get_img_path(
            self,
            edit: Edit,
            pixmap: pymupdf.Pixmap,
            directory: Path,
    ) -> Path:
        if pixmap is None:
            return None
        img_path = directory / f'{edit.xref}.png'
        pixmap.save(str(img_path))
        return img_path

    def get_synctex_outs_before(self, xref: int) -> list[SynctexOut]:
        # only query when key known to exist
        this_line = self.xref_to_line[xref] 
        return [
            sync_out for line, sync_out in self.xref_to_synctex.values()
            if line < this_line
        ]

    ##################################################
    ##                                              ##
    ##            Update annots_pdf_doc             ##
    ##                                              ##
    ##################################################    

    def save(self, filename=''):
        if not filename:
            filename = f'{self.annots_pdf.stem}-{self.script_name}.pdf'
        self.annots_pdf_doc.save(filename)

    def xref_update(self, xref: int, set_to: dict[str, tuple[str, str]]):
        for key, (type, value) in set_to.items():
            if type == 'string':
                value = f'({value})'
            self.annots_pdf_doc.xref_set_key(xref, key, value)
        return

    def update_from_tannot(self, tannot: XrefObj):
        set_to = {
            XrefObj.STATE_KEY: ('string', tannot.state),
            XrefObj.TITLE_KEY: ('string', self.user),
        }
        self.xref_update(tannot.xref, set_to)

##################################################
##                                              ##
##                Class external                ##
##                                              ##
##################################################

def get_annidx_to_line(latex_file: Path):
    with open(latex_file, 'r') as f:
        lines = f.readlines()
    annidx_to_line = {}
    found_anns = []
    line_start, line_end = None, None
    for line_no, line in enumerate(lines, start=1):
        ann_match = re.search('%% Annotation (?P<index>[0-9]+)', line)
        if ann_match is not None:
            found_anns.append(int(ann_match.group('index')))
            continue
        if found_anns:
            start_snippet_match = re.search(r'^%⭣ ⭣ ⭣', line)
            if start_snippet_match is not None:
                line_start = line_no + 1
                continue
        if line_start is not None:
            end_snippet_match = re.search(r'^%⭡ ⭡ ⭡', line)
            if end_snippet_match is not None:
                line_end = line_no - 1
        found_annin_lines = (
            line_start is not None and
            line_end is not None and
            found_anns
        )
        if found_annin_lines:
            if not line_end >= line_start:
                raise RuntimeError(
                    f"line_start > line_end: {line_start} > {line_end}"
                )
            line_middle = (line_start + line_end) // 2
            for annidx in found_anns:
                annidx_to_line[annidx] = line_middle
            found_anns = []
            line_start = None
            line_end = None
    return annidx_to_line

def get_isolated_edit_pixmap(
        man: Manuscript,
        edit: Edit,
        image_rectangle: pymupdf.Rect
) -> pymupdf.Pixmap:
    tmp_doc_obj = pymupdf.open(man.annots_pdf)
    tmp_page = tmp_doc_obj[edit.pageno]
    for ann in tmp_page.annots():
        if not (ann.xref == edit.xref or ann.xref == edit.related_xref):
            # for some reason tmp_page.delete_annot(ann) doesn't work
            tmp_doc_obj.xref_set_key(ann.xref, 'Rect', '[ 0 0 0 0 ]')
    r = edit.annot_rect
    circle_rect = pymupdf.Rect(
        r.x0 - ATTENTION_BOX_GROW,
        r.y0 - ATTENTION_BOX_GROW,
        r.x1 + ATTENTION_BOX_GROW,
        r.y1 + ATTENTION_BOX_GROW,
    )
    tmp_page.add_rect_annot(circle_rect)

    return tmp_page.get_pixmap(
        dpi=IMAGE_DPI,
        clip=image_rectangle,
        annots=SHOW_ANNS,
    )
    
def get_before_pixmap(man: Manuscript, edit: Edit) -> pymupdf.Pixmap:
    page = man.annots_pdf_doc[edit.pageno]
    page_width, page_height = page.rect.width, page.rect.height
    image_extend = man.ba_half_image_height
    
    im_x_start = IMAGE_X_START
    im_y_start = max(edit.annot_rect.y0 - image_extend, 0)
    im_x_end   = page_width
    im_y_end   = min(edit.annot_rect.y1 + image_extend, page_height)
    
    image_rectangle = pymupdf.Rect(
        im_x_start,
        im_y_start,
        im_x_end,
        im_y_end
    )
    pixmap = get_isolated_edit_pixmap(man, edit, image_rectangle)
    return pixmap

def choose_synctex_out(
        man: Manuscript,
        edit: Edit,
        synctex_outs: list[SynctexOut]
) -> SynctexOut:
    """
    If SyncTeX outputs have different *pages*
    we choose the first one that is greater than the
    maximum of the previous SyncTeX pages or, if there
    aren't any such cases, just the first output like usual
    """
    outs_before = man.get_synctex_outs_before(edit.xref)
    if not outs_before:
        return synctex_outs[0]
    min_page_thresh = max(ob.page for ob in outs_before)
    # heuristic: bias toward later pages if synctex_outs offer multiple
    filtered_outs = [
        sync_out for sync_out in synctex_outs
        if sync_out.page > min_page_thresh
    ]
    if not filtered_outs:
        return synctex_outs[0]
    else:
        return filtered_outs[0]

def acquire_synctex_out(man: Manuscript, edit: Edit):
    line = man.xref_to_line.get(edit.xref, None)
    if line is None:
        logger.warning(f"Annot with xref {edit.xref} was not written in {man.latex_file}")
        return
    synctex_result = sync.run_synctex_view(line, man.latex_file.absolute(), man.latex_pdf.absolute())
    try:
        synctex_outs = sync.parse_synctex_view(synctex_result)
    except RuntimeError as e:
        logger.warning(f"SyncTeX could not locate output of line {line} from {man.latex_file}: {e}")
        return

    chosen_out = choose_synctex_out(man, edit, synctex_outs)
    man.set_synctex_out(edit.xref, chosen_out)

def get_after_pixmap(man: Manuscript, edit: Edit) -> pymupdf.Pixmap | None:
    if edit.xref not in man.xref_to_synctex:
        return None
    line, chosen_out = man.xref_to_synctex[edit.xref]
    pageno, x, y = (
        chosen_out.page,
        chosen_out.x,
        chosen_out.y,
    )
    # ic(edit.xref, pageno, x, y)
    page = man.generated_pdf_doc[pageno]
    edit_rect_nudge = edit.annot_rect.height / 2
    image_extend = man.ba_half_image_height

    im_x_start = IMAGE_X_START
    im_y_start = max(0, y - image_extend - edit_rect_nudge)
    im_x_end   = page.cropbox.width
    im_y_end   = min(y + image_extend + edit_rect_nudge, page.cropbox.height)
    
    image_rectangle = pymupdf.Rect(
        im_x_start,
        im_y_start,
        im_x_end,
        im_y_end,
    )
    return page.get_pixmap(
        clip=image_rectangle,
        dpi=IMAGE_DPI,
    )
