import logging
logger = logging.getLogger(__name__)
import pymupdf
import json
import re
import tempfile
import sys
import getpass

from pathlib import Path
from icecream import ic

import texpdfedits.utils as utils
import texpdfedits.extractanns as extractanns
import texpdfedits.vercorr.sync as sync

from texpdfedits.extractanns import Edit, XrefObj
from texpdfedits.vercorr.sync import SynctexOut

IMAGE_X_START = 30 # in points (TeX's big points)
IMAGE_AROUND = 45 # in points

IMAGE_DPI = 125
SHOW_ONLY_ISOLATED_EDITS = True
SHOW_ANNS = True

BEFORE_IMG_SUBDIR = 'before'
AFTER_IMG_SUBDIR = 'after'

ATTENTION_BOX_GROW = 7.5

class GuiAnnot:
    def __init__(
            self,
            man: Manuscript,
            edit: Edit,
    ):  
        self.pageno = edit.pageno # 0-based
        self.page_label = edit.page_label
        type_int, type_str = edit.type
        self.type = type_str
        self.comment = edit.message['comment']
        self.responses = edit.message['responses']
        
        # edit.selection, ..., edit.annot_rect maybe later
        
        self.xref = edit.xref
        self.related_xref = edit.related_xref
        
        self.checkmark = edit.checkmark
        self.status = edit.status
        
        # checkmark and status can be None in which case we'll
        # initialize them ourselves by creating new text annotations
        
        if self.checkmark is None:
            state_model = XrefObj.CHECKMARK_MODEL
            state = XrefObj.UNCHECKED
            self.checkmark = self.initialize_tannot(man, state_model, state)
            
        if self.status is None:
            state_model = XrefObj.STATUS_MODEL
            state = XrefObj.STATUS_NONE
            self.status = self.initialize_tannot(man, state_model, state)
            
        self.before_path = man.xref_to_before_after_images[self.xref][BEFORE_IMG_SUBDIR]
        self.after_path = man.xref_to_before_after_images[self.xref][AFTER_IMG_SUBDIR]            

    def initialize_tannot(self, man: Manuscript, state_model: str, state: str) -> XrefObj:
        set_to = {
            XrefObj.FLAG_KEY: ('xref', XrefObj.FLAG_IN_USE),
            XrefObj.IRT_KEY: ('xref', f'{self.xref} 0 R'),
            XrefObj.STATE_MODEL_KEY: ('string', state_model),
            XrefObj.STATE_KEY: ('string', state),
            XrefObj.TITLE_KEY: ('string', man.user_title),
        }
        page = man.obj[self.pageno]
        local_tannot = page.add_text_annot((0,0), '', icon='Comment')
        ta_xref = local_tannot.xref
        man.xref_update(ta_xref, set_to)
        return XrefObj(ta_xref, state_model, state, man.user_title)

class Manuscript:
    """Represents corrections manuscript"""
    def __init__(
            self,
            annots_pdf: str | Path,
            latex_file: str | Path,
            cl_args: argparse.Namespace,
    ):
        annots_pdf = Path(annots_pdf)
        latex_file = Path(latex_file)
        if not annots_pdf.exists():
            raise FileNotFoundError(f"Could not find annotated PDF '{annots_pdf}'")
        self.annots_pdf = annots_pdf
        self.obj = pymupdf.open(self.annots_pdf)        
        self.edits, self.target_num_edits = extractanns.getEdits(
            self.annots_pdf,
            **{'adjust_annots': False},
        )
        annin_file = utils.replace_suffix(
            self.annots_pdf,
            'annin',
        )
        if not annin_file.exists():
            raise FileNotFoundError(f"Could not find {annin_file}")
        with open(annin_file, 'r') as f:
            self.xref_to_annidx = {}
            for line in f.readlines():
                line_json = json.loads(line)
                self.xref_to_annidx[line_json['xref']] = line_json['index']
        if not latex_file.exists():
            raise FileNotFoundError(f"Could not find LaTeX file '{latex_file}'")
        
        self.latex_file = latex_file
        self.annidx_to_line = get_annidx_to_lines(latex_file)
        self.xref_to_line = {
            xref : self.annidx_to_line.get(annidx, None)
            for xref, annidx in self.xref_to_annidx.items()
        }

        # compile
        if cl_args.gen_synctex:
            utils.compile_tex(
                self.latex_file,
                cl_args.compiler,
                '-synctex=1',
            )
            dont_delete = [
                '.synctex.gz',
                '.synctex',
                '.pdf',
            ]
            utils.delete_intermediate_latex(self.latex_file, ignore=dont_delete)
            
        self.latex_pdf = utils.replace_suffix(
            self.latex_file,
            'pdf',
        )
        if not self.latex_pdf.exists():
            raise FileNotFoundError(f"Could not find PDF generated by LaTeX file '{self.latex_pdf}'")
        self.generated_pdf_doc = pymupdf.open(self.latex_pdf.name)
        self.xref_to_synctex = {}

        self.temp_dir = tempfile.TemporaryDirectory()
        self.before_after_dir = Path(self.temp_dir.name)
        self.build_xref_to_before_after()

        self.user_title = getpass.getuser()

        # GUI Annotations
        self.gui_annotations = [
            GuiAnnot(self, edit)
            for edit in self.edits
        ]
        self.script_name = Path(sys.argv[0]).name

    def save(self, filename=''):
        if not filename:
            filename = f'{self.annots_pdf.stem}-{self.script_name}.pdf'
        self.obj.save(filename)

    def xref_update(self, xref: int, set_to: dict[str, tuple[str, str]]):
        for key, (type, value) in set_to.items():
            if type == 'string':
                value = f'({value})'
            self.obj.xref_set_key(xref, key, value)
        return

    def update_from_tannot(self, tannot: XrefObj):
        set_to = {
            XrefObj.STATE_KEY: ('string', tannot.state),
            XrefObj.TITLE_KEY: ('string', self.user_title),
        }
        self.xref_update(tannot.xref, set_to)

    def save_and_get_img_path(
            self,
            edit: Edit,
            pixmap: pymupdf.Pixmap,
            subdir: Path,
    ):
        if pixmap is None:
            return None
        img_path = self.before_after_dir / subdir / f'{edit.xref}.png'
        pixmap.save(str(img_path))
        return img_path
        
    def build_xref_to_before_after(self):
        logger.info("Generating before and after images...")
        self.xref_to_before_after_images = {}
        
        before_subdir = self.before_after_dir / BEFORE_IMG_SUBDIR
        Path.mkdir(before_subdir)
        
        after_subdir = self.before_after_dir / AFTER_IMG_SUBDIR
        Path.mkdir(after_subdir)

        num_edits = len(self.edits)
        bar = utils.TextProgressBar(num_edits, show_per=max(1, num_edits // 100))
        bar.showSize()
        for edit in self.edits:
            before_pixmap = get_before_pixmap(self, edit)
            before_img_path = self.save_and_get_img_path(
                edit,
                before_pixmap,
                before_subdir,
            )
            after_pixmap = get_after_pixmap(self, edit)
            after_img_path = self.save_and_get_img_path(
                edit,
                after_pixmap,
                after_subdir,
            )
            self.xref_to_before_after_images[edit.xref] = {
                'before': before_img_path,
                'after': after_img_path,
            }
            bar.addProgress()
        bar.end()
        logger.info("Done")

    def set_synctex_out(
            self,
            xref: int,
            synctex_out: SynctexOut,
    ):
        line = self.xref_to_line[xref]
        self.xref_to_synctex[xref] = line, synctex_out

    def _get_synctex_outs_before(self, xref: int) -> list[SynctexOut]:
        # only query when key known to exist
        this_line = self.xref_to_line[xref] 
        return [
            sync_out for line, sync_out in self.xref_to_synctex.values()
            if line < this_line
        ]

def get_annidx_to_lines(latex_file):
    with open(latex_file, 'r') as f:
        lines = f.readlines()
    annidx_to_line = {}
    found_anns = []
    line_start, line_end = None, None
    for line_no, line in enumerate(lines, start=1):
        ann_match = re.search('%% Annotation (?P<index>[0-9]+)', line)
        if ann_match is not None:
            found_anns.append(int(ann_match.group('index')))
            continue
        if found_anns:
            start_snippet_match = re.search(r'^%⭣ ⭣ ⭣', line)
            if start_snippet_match is not None:
                line_start = line_no + 1
                continue
        if line_start is not None:
            end_snippet_match = re.search(r'^%⭡ ⭡ ⭡', line)
            if end_snippet_match is not None:
                line_end = line_no - 1
        found_annin_lines = (
            line_start is not None and
            line_end is not None and
            found_anns
        )
        if found_annin_lines:
            if not line_end >= line_start:
                raise RuntimeError(
                    f"line_start > line_end: {line_start} > {line_end}"
                )
            line_middle = (line_start + line_end) // 2
            for annidx in found_anns:
                annidx_to_line[annidx] = line_middle
            found_anns = []
            line_start = None
            line_end = None
    return annidx_to_line

def get_isolated_edit_pixmap(
        doc: Manuscript,
        edit: Edit,
        image_rectangle: pymupdf.Rect
) -> pymupdf.Pixmap:
    tmp_doc_obj = pymupdf.open(doc.annots_pdf)
    tmp_page = tmp_doc_obj[edit.pageno]
    for ann in tmp_page.annots():
        if not (ann.xref == edit.xref or ann.xref == edit.related_xref):
            # for some reason tmp_page.delete_annot(ann) doesn't work
            tmp_doc_obj.xref_set_key(ann.xref, 'Rect', '[ 0 0 0 0 ]')
    r = edit.annot_rect
    circle_rect = pymupdf.Rect(
        r.x0 - ATTENTION_BOX_GROW,
        r.y0 - ATTENTION_BOX_GROW,
        r.x1 + ATTENTION_BOX_GROW,
        r.y1 + ATTENTION_BOX_GROW,
    )
    tmp_page.add_rect_annot(circle_rect)

    return tmp_page.get_pixmap(
        dpi=IMAGE_DPI,
        clip=image_rectangle,
        annots=SHOW_ANNS,
    )
    
def get_before_pixmap(doc: Manuscript, edit: Edit) -> pymupdf.Pixmap:
    page = doc.obj[edit.pageno]
    page_width, page_height = page.rect.width, page.rect.height
    
    im_x_start = IMAGE_X_START
    im_y_start = max(edit.annot_rect.y0 - IMAGE_AROUND, 0)
    im_x_end   = page_width
    im_y_end   = min(edit.annot_rect.y1 + IMAGE_AROUND, page_height)
    
    image_rectangle = pymupdf.Rect(
        im_x_start,
        im_y_start,
        im_x_end,
        im_y_end
    )
    if SHOW_ONLY_ISOLATED_EDITS:
        pixmap = get_isolated_edit_pixmap(doc, edit, image_rectangle)
    else:
        pixmap = page.get_pixmap(
            dpi=IMAGE_DPI,
            clip=image_rectangle,
            annots=SHOW_ANNS,
        )
    return pixmap

def choose_synctex_out(
        doc: Manuscript,
        edit: Edit,
        synctex_outs: list[SynctexOut]
) -> SynctexOut:
    """
    If SyncTeX outputs have different *pages*
    we choose the first one that is greater than the
    maximum of the previous SyncTeX pages or, if there
    aren't any such cases, just the first output like usual
    """
    outs_before = doc._get_synctex_outs_before(edit.xref)
    if not outs_before:
        return synctex_outs[0]
    min_page_thresh = max(ob.page for ob in outs_before)
    # heuristic: bias toward later pages if synctex_outs offer multiple
    filtered_outs = [
        sync_out for sync_out in synctex_outs
        if sync_out.page > min_page_thresh
    ]
    if not filtered_outs:
        return synctex_outs[0]
    else:
        return filtered_outs[0]

def get_after_pixmap(doc: Manuscript, edit: Edit) -> pymupdf.Pixmap | None:
    line = doc.xref_to_line.get(edit.xref, None)
    if line is None:
        logger.warning(f"Annot with xref {edit.xref} was not written in {doc.latex_file}")
        return None
    synctex_result = sync.run_synctex_view(line, doc.latex_file.absolute(), doc.latex_pdf.absolute())
    try:
        synctex_outs = sync.parse_synctex_view(synctex_result)
    except RuntimeError as e:
        logger.warning(f"SyncTeX could not locate output of line {line} from {doc.latex_file}: {e}")
        return None

    chosen_out = choose_synctex_out(doc, edit, synctex_outs)
    doc.set_synctex_out(edit.xref, chosen_out)

    pageno, x, y = (
        chosen_out.page,
        chosen_out.x,
        chosen_out.y,
    )
    # ic(edit.xref, pageno, x, y)
    page = doc.generated_pdf_doc[pageno]
    edit_rect_nudge = edit.annot_rect.height / 2

    im_x_start = IMAGE_X_START
    im_y_start = max(0, y - IMAGE_AROUND - edit_rect_nudge)
    im_x_end   = page.cropbox.width
    im_y_end   = min(y + IMAGE_AROUND + edit_rect_nudge, page.cropbox.height)
    
    image_rectangle = pymupdf.Rect(
        im_x_start,
        im_y_start,
        im_x_end,
        im_y_end,
    )
    return page.get_pixmap(
        clip=image_rectangle,
        dpi=IMAGE_DPI,
    )
        
        
